name: Java CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  backend-build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: '8.8' # ★最新の9系によるエラーを回避するため、安定版の8.8を明示的に指定
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build and Test with Gradle
      run: ./gradlew build --no-daemon
